phrase:
  access_token: 6793ef4095e83447bdf7942e0d4eba5738cb28b610b8676543df7ee21156c929
  project_id: 124be7307f9aff1a6c33a74b0de8965d
  file format: xml
  
  push:
    sources:
    - file: ./original/es.xml
      params:
        file_format: xml
        locale_id: c94a67ef858613182e16699b890e40eb
        update_translations: false
        
        
  pull:
    targets:
    - file: ./traduccion/<locale_code>.xml
      params: 
        locale_id: db657d6183283c7bace0cbe8b7a34440
        file_format: xml
